theme: jekyll-theme-minimal
title: Neon.js
description: Neon.js is a browser-based music notation editor written in JavaScript. The editor can be used to manipulate digitally encoded early musical scores in square-note notation.
